CitasMedicas/CitasMedicas/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CitasMedicas.Models
{
    public class LoginViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Display(Name = "Clave")]
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Display(Name = "Recordar")]
        public bool RememberMe { get; set; }
    }
}

CitasMedicas/CitasMedicas/Models/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CitasMedicas.Models
{
    public class RegisterViewModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

CitasMedicas/CitasMedicas/Controllers/CitasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CitasMedicas.Data;
using CitasMedicas.Models;

namespace CitasMedicas.Controllers
{
    public class CitasController : Controller
    {
        private readonly CitasMedicasContext _context;

        public CitasController(CitasMedicasContext context)
        {
            _context = context;
        }

        // GET: Citas
        public async Task<IActionResult> Index()
        {
            string? userName = HttpContext.Session.GetString("UserName");
            string? TipoUsuario = HttpContext.Session.GetString("TipoUsuario");
            if (userName != null &&( TipoUsuario=="Medico"))
            {
                var citasMedicasContext = _context.Citas.Include(c => c.Medico).Include(c => c.Paciente).Where(c => c.Medico.Usuario.UserName == userName && c.EstadoCita == 1);
                return View("Index", await citasMedicasContext.ToListAsync());
            }
            else if (userName != null && (TipoUsuario == "Paciente"))
            {
                var citasMedicasContext = _context.Citas.Include(c => c.Medico).Include(c => c.Paciente).Where(c => c.Paciente.Usuario.UserName == userName);
                return View("Index", await citasMedicasContext.ToListAsync());
            }
            else
            {
                var citasMedicasContext = _context.Citas.Include(c => c.Medico).Include(c => c.Paciente);
                return View(await citasMedicasContext.ToListAsync());
            }
            
        }
        // GET: Citas
        public async Task<IActionResult> CitasMedico()
        {
            string? userName = HttpContext.Session.GetString("UserName");
            if(userName != null)
            {
                var citasMedicasContext = _context.Citas.Include(c => c.Medico).Include(c => c.Paciente).Where(c => c.Medico.Usuario.UserName == userName);
                return View("Index",await citasMedicasContext.ToListAsync());
            }
            else
            {
                return NotFound();
            }
            
        }

        // GET: Citas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Citas == null)
            {
                return NotFound();
            }

            var cita = await _context.Citas
                .Include(c => c.Medico)
                .Include(c => c.Paciente)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cita == null)
            {
                return NotFound();
            }

            return View(cita);
        }


        // GET: Citas/Create
        [HttpPost]
        public IActionResult ReturnCreate([Bind("PacienteId,PacienteNombre,EspecialidadId")] CreateCitaViewModel createCitaViewModel)
        {
            ViewData["ConsultorioId"] = new SelectList(
                _context.Consultorios, 
                "Id",              
                "NombreConsultorio"
            );
            ViewData["MedicoId"] = new SelectList(
                _context.Medicos.Where(m=>m.Especialidades.FirstOrDefault(e=>e.Id== createCitaViewModel.EspecialidadId) !=null),
                "Id",
                "NombreCompleto"
            );
            ViewData["PacienteId"] = new SelectList(
                _context.Pacientes,
                "Id",
                "NombrePaciente"
            );
            ViewBag.NombrePaciente = createCitaViewModel.PacienteNombre;
            ViewBag.IdPaciente = createCitaViewModel.PacienteId;
            return View("Create");
        }

        // POST: Citas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FechaCita,HoraCita,MedicoId,DiagnosticoId,ConsultorioId,PacienteId,EstadoCita")] Cita cita)
        {
            if (ModelState.IsValid)
            {
                var citaEncontrada = await _context.Citas
                .Where(c => c.HoraCita == cita.HoraCita && c.FechaCita == cita.FechaCita
                &&c.MedicoId==cita.MedicoId)
                .FirstOrDefaultAsync();
                var citaEncontrada2 = await _context.Citas
                .Where(c => c.HoraCita == cita.HoraCita && c.FechaCita == cita.FechaCita
                && c.PacienteId == cita.PacienteId)

                .FirstOrDefaultAsync();
                var citaEncontrada3 = await _context.Citas
                .Where(c => c.HoraCita == cita.HoraCita && c.FechaCita == cita.FechaCita)

                .FirstOrDefaultAsync();


                if (citaEncontrada != null || citaEncontrada2 != null || citaEncontrada3 != null)
                {
                    
                    if (citaEncontrada != null) ModelState.AddModelError("MedicoId", "El medico esta ocupado");
                    if (citaEncontrada2 != null) ModelState.AddModelError("PacienteId", "Paciente ya tiene una cita en ese horario");
                    if (citaEncontrada3 != null) ModelState.AddModelError("ConsultorioId", "El consultorio está ocupado");

            //        ViewData["ConsultorioId"] = new SelectList(
            //    _context.Consultorios,
            //    "Id",
            //    "NombreConsultorio",
            //    cita.ConsultorioId
            //);
                    ViewData["MedicoId"] = new SelectList(
                        _context.Medicos,
                        "Id",
                        "NombreCompleto",
                        cita.MedicoId
                    );
                    ViewData["PacienteId"] = new SelectList(
                        _context.Pacientes,
                        "Id",
                        "NombrePaciente",
                        cita.PacienteId
                    );
                    return View(cita);
                }


                _context.Add(cita);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ConsultorioId"] = new SelectList(
                _context.Consultorios,
                "Id",
                "NombreConsultorio"
            );
            ViewData["MedicoId"] = new SelectList(
                _context.Medicos,
                "Id",
                "NombreCompleto"
            );
            ViewData["PacienteId"] = new SelectList(
                _context.Pacientes,
                "Id",
                "NombrePaciente"
            );
            return View(cita);
        }

        // GET: Citas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Citas == null)
            {
                return NotFound();
            }

            //var cita = await _context.Citas.FindAsync(id);
            var cita = await _context.Citas
                .Include(c => c.Medico)
                .Include(c => c.Paciente)
                .Include(c => c.Receta).ThenInclude(mr => mr.Medicamento)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cita == null)
            {
                return NotFound();
            }
            
            ViewData["MedicoId"] = new SelectList(
                _context.Medicos,
                "Id",
                "NombreCompleto",
                cita.MedicoId
            );
            ViewData["PacienteId"] = new SelectList(
                _context.Pacientes,
                "Id",
                "NombrePaciente",
                cita.PacienteId
            );
            HistoriaClinica historiaClinica = await _context.HistoriasClinicas
                .Where(h => h.PacienteId == cita.PacienteId)
                .FirstOrDefaultAsync();

            ViewBag.HistoriaClinica = historiaClinica;
            return View(cita);
        }

        // POST: Citas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FechaCita,HoraCita,MedicoId,DiagnosticoId,ConsultorioId,PacienteId,EstadoCita,Diagnostico")] Cita cita)
        {

            if (HttpContext.Session.GetString("TipoUsuario") == "Paciente")
            {
                var citaPaciente= await _context.Citas.FindAsync(id);
                if(citaPaciente!=null)
                {
                    citaPaciente.EstadoCita = 3;
                    _context.Update(citaPaciente);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                
            }

            if (id != cita.Id)
            {
                return NotFound();
            }
            
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cita);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CitaExists(cita.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //ViewData["ConsultorioId"] = new SelectList(
            //    _context.Consultorios,
            //    "Id",
            //    "NombreConsultorio",
            //    cita.ConsultorioId
            //);
            
            

CitasMedicas/CitasMedicas/Views/Shared/AccessDenied.cshtml
@model LoginViewModel
@{
    Layout = null; // Esto desactiva el layout para esta vista
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CitasMedicas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sidebar.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/font-awesome.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CitasMedicas.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.0/css/dataTables.dataTables.css" />
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-color: #f8f9fa;
        }

        .access-denied-container {
            max-width: 400px;
            width: 100%;
            padding: 20px;
            background: #fff;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
            text-align: center;
        }

            .access-denied-container h2 {
                color: #dc3545;
            }

            .access-denied-container p {
                margin: 20px 0;
            }
    </style>
</head>

<body>
    <div class="access-denied-container">
        <h2>Access Denied</h2>
        <p>You do not have permission to access this page.</p>
        <a href="~/Usuario/Login" class="btn btn-primary">Go to Login</a>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>


    <script src="https://cdn.datatables.net/2.1.0/js/dataTables.js"></script>

</body>
</html>

CitasMedicas/CitasMedicas/Views/Shared/Login.cshtml
@model LoginViewModel
@{
    Layout = null; // Esto desactiva el layout para esta vista
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CitasMedicas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sidebar.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/font-awesome.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CitasMedicas.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.0/css/dataTables.dataTables.css" />
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-color: #f8f9fa;
        }

        .login-container {
            max-width: 400px;
            width: 100%;
            padding: 20px;
            background: #fff;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
    </style>
</head>

<body>
    <div class="login-container">
        <h2 class="text-center">Login</h2>
        <form asp-action="Login" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email">Email</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password">Password</label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <input asp-for="RememberMe" type="checkbox" class="form-check-input" />
                <label asp-for="RememberMe" class="form-check-label">Remember me</label>
            </div>
            <button type="submit" class="btn btn-primary btn-block">Login</button>
        </form>
    </div>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
 

        <script src="https://cdn.datatables.net/2.1.0/js/dataTables.js"></script>

</body>
</html>

CitasMedicas/CitasMedicas/Views/Shared/Register.cshtml
@model RegisterViewModel


@{
    Layout = null; // Esto desactiva el layout para esta vista
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CitasMedicas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sidebar.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/font-awesome.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CitasMedicas.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.0/css/dataTables.dataTables.css" />
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-color: #f8f9fa;
        }

        .login-container {
            max-width: 400px;
            width: 100%;
            padding: 20px;
            background: #fff;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
    </style>
</head>

<body>
    <div class="login-container">
        <h2>Register</h2>
        <form asp-action="Register" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConfirmPassword"></label>
                <input asp-for="ConfirmPassword" class="form-control" />
                <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Register</button>
        </form>

    </div>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
 

        <script src="https://cdn.datatables.net/2.1.0/js/dataTables.js"></script>

</body>
</html>

CitasMedicas/CitasMedicas/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@{
    string strTipoUsuario = HttpContextAccessor.HttpContext.Session.GetString("TipoUsuario");
    int? pacienteId = HttpContextAccessor.HttpContext.Session.GetInt32("PacienteId");

}

@inject IHttpContextAccessor HttpContextAccessor
@{
    // Obtener el path actual
    var path = Context.Request.Path.Value;
    // Puedes dividir el path en partes si necesitas para crear breadcrumbs específicos
    var pathSegments = path.Trim('/').Split('/');
    var breadcrumbItems = new List<string>();

    // Agregar "Principal" como primer item del breadcrumb
    breadcrumbItems.Add("Dashboard");

    // Agregar los segmentos del path al breadcrumb
    foreach (var segment in pathSegments)
    {
        breadcrumbItems.Add(segment);
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CitasMedicas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sidebar.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/font-awesome.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CitasMedicas.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.0/css/dataTables.dataTables.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark sticky-top">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="/">Citas Médicas</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle">
                <i class="fas fa-bars"></i>
            </button>

            <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user fa-fw"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        @if (HttpContextAccessor.HttpContext.Session.GetInt32("EstadoLogin") != 1)
                            @Html.Raw($"<li'><a class='dropdown-item' href='{Url.Action("Login", "Usuario")}'>Iniciar Sesión</a></li>")
                        else
                        {
                            @Html.Raw($"<li'><a class='dropdown-item' href='{Url.Action("Logout", "Usuario")}'>Cerrar Sesión</a></li>")
                            
                        }
                        

                        
                    </ul>
                </li>
            </ul>
        </nav>
    </header>
    <div class="container-fluid">
        <div class="row">

            <div class="col-md-2" id="sidebar-wrapper">

                <div class="sidebar-heading">Módulos Hospital</div>
                <div class="list-group list-group-flush">

                    
                    @Html.Raw($"<div class='list-group'><a href='{Url.Action("Dashboard", "Home", new { area = "" })}'><i class='fas fa-tachometer-alt i-class'></i>Dashboard</a></div>")
                    @if (strTipoUsuario == "Admin")
                    {
                        @Html.Raw($"<div class='list-group'><a href='{Url.Action("Index", "Usuario")}'><i class='fas fa-users i-class'></i>Usuarios</a></div>")
                    }

                    @if (strTipoUsuario == "Admin")
                    @Html.Raw($"<div class='list-group'><a href='{Url.Action("Index", "Pacientes")}'><i class='fas fa-id-card i-class'></i>Pacientes</a></div>")
                    @if (strTipoUsuario == "Admin")
                    @Html.Raw($"<div class='list-group'><a href='{Url.Action("Index", "Medicos")}'><i class='fas fa-clinic-medical i-class'></i>Médicos</a></div>")
                    @* @if (new[] { "Admin", "Medico", "" }.Contains(strTipoUsuario))
                    @Html.Raw($"<div class='list-group'><a href='{Url.Action("Index", "Citas")}'><i class='fas fa-calendar i-class'></i>Citas</a></div>") *@
                    @* @if (strTipoUsuario == "Admin") *@
                        @Html.Raw($"<div class='list-group'><a href='{Url.Action("Index", "Citas")}'><i class='fas fa-calendar i-class'></i>Citas</a></div>")
                    @* @if (strTipoUsuario == "Medico")
                        @Html.Raw($"<div class='list-group'><a href='{Url.Action("CitasMedico", "Citas")}'><i class='fas fa-calendar i-class'></i>Citas</a></div>") *@
                    @if (strTipoUsuario == "Admin")
                    @Html.Raw($"<div class='list-group'><a href='{Url.Action("Index", "Medicamentos")}'><i class='fas fa-medkit i-class'></i>Farmacia</a></div>")
                    @if (strTipoUsuario == "Admin")
                    @Html.Raw($"<div class='list-group'><a href='{Url.Action("Index", "Especialidades")}'><i class='fas fa-table i-class'></i>Especialidades</a></div>")
                    @if (strTipoUsuario == "Admin")
                    @Html.Raw($"<div class='list-group'><a href='{Url.Action("Index", "Consultorios")}'><i class='fas fa-table i-class'></i>Consultorios</a></div>")

                    @if (strTipoUsuario == "Admin" || strTipoUsuario == "Medico")
                    {
                        @Html.Raw($"<div class='list-group'><a href='{Url.Action("Index", "HistoriasClinicas")}'><i class='fas fa-table i-class'></i>Historias Clinicas</a></div>")
                    }
                    else
                    {
                        @Html.Raw($"<div class='list-group'><a href='{Url.Action("Details", "HistoriasClinicas", new { id = pacienteId })}'><i class='fas fa-table i-class'></i>Historias Clinicas</a></div>")
                    }

                    @if (strTipoUsuario == "Admin")
                        @Html.Raw($"<div class='list-group'><a href='{Url.Action("Index", "Enfermeras")}'><i class='fas fa-user-nurse i-class'></i>Enfermeras</a></div>")




                    @*@Html.ActionLink("Create Medicos", "Create", "Medicos", new { area = "" }, new { @class = "list-group" })*@
                </div>
            </div>
            <div class="col-md-10" id="page-content-wrapper">
                <div class="container-fluid p-1">

                    @* <ol class="breadcrumb mb-4 mt-4">
                        <li class="breadcrumb-item"><a href="index.html">Principal</a></li>
                        <li class="breadcrumb-item active">Medico</li>
                    </ol> *@
                    <ol class="breadcrumb mb-4 mt-4">
                        @for (var i = 0; i < breadcrumbItems.Count; i++)
                        {
                            <li class="breadcrumb-item @(i == breadcrumbItems.Count - 1 ? "active" : "")">
                                @if (i < breadcrumbItems.Count - 1)
                                {
                                    <a href="#">@breadcrumbItems[i]</a>
                                }
                                else
                                {
                                    @breadcrumbItems[i]
                                }
                            </li>
                        }
                    </ol>

                    <div class="card">
                        @* <div class="card-header">
                            <i class="fas fa-id-card me-1"></i> Lista Medicos
                        </div> *@

                        <div class="card-body">
                            @* <div class="row">
                                <div class="col-12">
                                    <button type="button" class="btn btn-primary">Crear Medico</button>
                                </div>
                            </div>


                            <hr /> *@
                            <div class="p-2">
                                @RenderBody()
                                @*<hr />*@

                            </div>
                            @*<footer>
                            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
                            </footer>*@
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CitasMedicas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)


    <script src="https://cdn.datatables.net/2.1.0/js/dataTables.js"></script>
    <script>
        $(document).ready(function () {
            $('#dataTableId').DataTable({
                responsive: true,
                "language": {
                    url: '//cdn.datatables.net/plug-ins/2.1.0/i18n/es-MX.json',
                }
            });
        });
    </script>

</body>
</html>