CitasMedicas/CitasMedicas/Controllers/HistoriasClinicasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CitasMedicas.Data;
using CitasMedicas.Models;

namespace CitasMedicas.Controllers
{
    public class HistoriasClinicasController : Controller
    {
        private readonly CitasMedicasContext _context;

        public HistoriasClinicasController(CitasMedicasContext context)
        {
            _context = context;
        }

        // GET: HistoriasClinicas
        public async Task<IActionResult> Index()
        {
            var citasMedicasContext = _context.HistoriasClinicas.Include(h => h.Paciente);
            return View(await citasMedicasContext.ToListAsync());
        }

        // GET: HistoriasClinicas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.HistoriasClinicas == null)
            {
                return NotFound();
            }

            var historiaClinica = await _context.HistoriasClinicas
                .Include(h => h.Paciente)
                .FirstOrDefaultAsync(m => m.Id == id);

            var citas= _context.Citas.Include(c=>c.Medico).Where(c => c.PacienteId == historiaClinica.PacienteId).ToList();   

            ViewBag.Citas = citas;


            if (historiaClinica == null)
            {
                return NotFound();
            }

            return View(historiaClinica);
        }

        // GET: HistoriasClinicas/Create
        public IActionResult Create()
        {
            ViewData["PacienteId"] = new SelectList(_context.Pacientes, "Id", "Id");
            return View();
        }

        // POST: HistoriasClinicas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Peso,Altura,PresionArterial,PacienteId")] HistoriaClinica historiaClinica)
        {
            if (ModelState.IsValid)
            {
                _context.Add(historiaClinica);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PacienteId"] = new SelectList(_context.Pacientes, "Id", "Id", historiaClinica.PacienteId);
            return View(historiaClinica);
        }

        // GET: HistoriasClinicas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.HistoriasClinicas == null)
            {
                return NotFound();
            }

            var historiaClinica = await _context.HistoriasClinicas.FindAsync(id);
            if (historiaClinica == null)
            {
                return NotFound();
            }
            ViewData["PacienteId"] = new SelectList(_context.Pacientes, "Id", "Id", historiaClinica.PacienteId);
            return View(historiaClinica);
        }

        // POST: HistoriasClinicas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Peso,Altura,PresionArterial,PacienteId")] HistoriaClinica historiaClinica)
        {
            if (id != historiaClinica.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(historiaClinica);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HistoriaClinicaExists(historiaClinica.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PacienteId"] = new SelectList(_context.Pacientes, "Id", "Id", historiaClinica.PacienteId);
            return View(historiaClinica);
        }

        // GET: HistoriasClinicas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.HistoriasClinicas == null)
            {
                return NotFound();
            }

            var historiaClinica = await _context.HistoriasClinicas
                .Include(h => h.Paciente)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (historiaClinica == null)
            {
                return NotFound();
            }

            return View(historiaClinica);
        }

        // POST: HistoriasClinicas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.HistoriasClinicas == null)
            {
                return Problem("Entity set 'CitasMedicasContext.HistoriasClinicas'  is null.");
            }
            var historiaClinica = await _context.HistoriasClinicas.FindAsync(id);
            if (historiaClinica != null)
            {
                _context.HistoriasClinicas.Remove(historiaClinica);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HistoriaClinicaExists(int id)
        {
          return (_context.HistoriasClinicas?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CitasMedicas/CitasMedicas/Views/HistoriasClinicas/Create.cshtml
@model CitasMedicas.Models.HistoriaClinica

@{
    ViewData["Title"] = "Create";
}

<h1>Creación</h1>

<h4>HistoriaClinica</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Peso" class="control-label"></label>
                <input asp-for="Peso" class="form-control" />
                <span asp-validation-for="Peso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Altura" class="control-label"></label>
                <input asp-for="Altura" class="form-control" />
                <span asp-validation-for="Altura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PresionArterial" class="control-label"></label>
                <input asp-for="PresionArterial" class="form-control" />
                <span asp-validation-for="PresionArterial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PacienteId" class="control-label"></label>
                <select asp-for="PacienteId" class ="form-control" asp-items="ViewBag.PacienteId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CitasMedicas/CitasMedicas/Views/HistoriasClinicas/Delete.cshtml
@model CitasMedicas.Models.HistoriaClinica

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>Está seguro de borrar?</h3>
<div>
    <h4>HistoriaClinica</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Peso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Peso)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Altura)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Altura)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PresionArterial)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PresionArterial)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Paciente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Paciente.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CitasMedicas/CitasMedicas/Views/HistoriasClinicas/Details.cshtml
@model CitasMedicas.Models.HistoriaClinica

@{
    ViewData["Title"] = "Details";
    var citasList = ViewBag.Citas as List<CitasMedicas.Models.Cita>;
}

<h1>Detailles</h1>

<div>
    <h4>HistoriaClinica</h4>
    <hr />
    <dl class="row">
        @* <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Peso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Peso)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Altura)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Altura)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PresionArterial)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PresionArterial)
        </dd> *@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Paciente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Paciente.Id)
        </dd>
    </dl>

    <dl class="row">
        <table class="table" id="dataTableId">
            <thead>
                <tr>
                    <th>
                        @* @Html.DisplayNameFor(model => model.CitasHistoriaClinica.FechaCita) *@
                        Fecha
                    </th>
                    <th>
                        @* @Html.DisplayNameFor(model => model.HoraCita) *@
                        Hora
                    </th>
                    <th>
                        @* @Html.DisplayNameFor(model => model.Medico) *@
                        Medico
                    </th>
                    <th>
                        @* @Html.DisplayNameFor(model => model.Diagnostico) *@
                        Diagnostico
                    </th>
                    @* <th>
                    @Html.DisplayNameFor(model => model.Consultorio)
                    </th> *@
                    <th>
                        @* @Html.DisplayNameFor(model => model.Paciente) *@
                        Paciente
                    </th>
                    <th>
                        @* @Html.DisplayNameFor(model => model.EstadoCita) *@
                        Estado
                    </th>
                    
                </tr>
            </thead>
            <tbody>
                @foreach (var item in citasList)
                {
                    <tr>
                        <td>
                            @item.FechaCita.ToString("dd-MM-yyyy")

                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.HoraCita)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Medico.NombreCompleto)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Diagnostico)
                        </td>
                        @* <td>
                    @Html.DisplayFor(modelItem => item.Consultorio.NombreConsultorio)
                    </td> *@
                        <td>
                            @Html.DisplayFor(modelItem => item.Paciente.NombrePaciente)
                        </td>
                        <td>
                            @* @Html.DisplayFor(modelItem => item.EstadoCita) *@
                            @(item.EstadoCita == 1 ? "Agendada" : (item.EstadoCita == 2 ? "Atendida" : "Cancelada"))
                        </td>
                        
                    </tr>
                }
            </tbody>
        </table>

    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CitasMedicas/CitasMedicas/Views/HistoriasClinicas/Edit.cshtml
@model CitasMedicas.Models.HistoriaClinica

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Historia Clinica</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Peso" class="control-label"></label>
                <input asp-for="Peso" class="form-control" />
                <span asp-validation-for="Peso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Altura" class="control-label"></label>
                <input asp-for="Altura" class="form-control" />
                <span asp-validation-for="Altura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PresionArterial" class="control-label"></label>
                <input asp-for="PresionArterial" class="form-control" />
                <span asp-validation-for="PresionArterial" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PacienteId" class="control-label"></label>
                <select asp-for="PacienteId" class="form-control" asp-items="ViewBag.PacienteId"></select>
                <span asp-validation-for="PacienteId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CitasMedicas/CitasMedicas/Views/HistoriasClinicas/Index.cshtml
@model IEnumerable<CitasMedicas.Models.HistoriaClinica>

@{
    ViewData["Title"] = "Index";
}

<h1>HISTORIA CLÍNICA</h1>

@* <p>
    <a asp-action="Create">Crear</a>
</p> *@
<table class="table" id="dataTableId">
    <thead>
        <tr>
            @* <th>
                @Html.DisplayNameFor(model => model.Peso)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Altura)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PresionArterial)
            </th> *@
            <th>
                @Html.DisplayNameFor(model => model.Paciente)
            </th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            @* <td>
                @Html.DisplayFor(modelItem => item.Peso)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Altura)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PresionArterial)
            </td> *@
            <td>
                @Html.DisplayFor(modelItem => item.Paciente.NombrePaciente)
            </td>
            <td>
                    <div class="actionsContainer">
                        @* @Html.Raw($"<a href='{Url.Action("Edit", "HistoriasClinicas", new { id = item.Id })}' class='btn btn-warning tableActionsBtn'>Editar</a>") *@
                        @Html.Raw($"<a href='{Url.Action("Details", "HistoriasClinicas", new { id = item.Id })}' class='btn btn-primary tableActionsBtn'>Detalles</a>")
                        @* @Html.Raw($"<a href='{Url.Action("Delete", "HistoriasClinicas", new { id = item.Id })}' class='btn btn-danger tableActionsBtn'>Eliminar</a>") *@
                    </div>
                
            </td>
        </tr>
}
    </tbody>
</table>