CitasMedicas/CitasMedicas/Controllers/EspecialidadesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CitasMedicas.Data;
using CitasMedicas.Models;

namespace CitasMedicas.Controllers
{
    public class EspecialidadesController : Controller
    {
        private readonly CitasMedicasContext _context;

        public EspecialidadesController(CitasMedicasContext context)
        {
            _context = context;
        }

        // GET: Especialidades
        public async Task<IActionResult> Index()
        {
              return _context.Especialidades != null ? 
                          View(await _context.Especialidades.ToListAsync()) :
                          Problem("Entity set 'CitasMedicasContext.Especialidades'  is null.");
        }

        // GET: Especialidades/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Especialidades == null)
            {
                return NotFound();
            }

            var especialidad = await _context.Especialidades
                .FirstOrDefaultAsync(m => m.Id == id);
            if (especialidad == null)
            {
                return NotFound();
            }

            return View(especialidad);
        }

        // GET: Especialidades/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Especialidades/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DescripcionEspecialidad")] Especialidad especialidad)
        {
            if (ModelState.IsValid)
            {
                _context.Add(especialidad);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(especialidad);
        }

        // GET: Especialidades/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Especialidades == null)
            {
                return NotFound();
            }

            var especialidad = await _context.Especialidades.FindAsync(id);
            if (especialidad == null)
            {
                return NotFound();
            }
            return View(especialidad);
        }

        // POST: Especialidades/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DescripcionEspecialidad")] Especialidad especialidad)
        {
            if (id != especialidad.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(especialidad);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EspecialidadExists(especialidad.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(especialidad);
        }

        // GET: Especialidades/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Especialidades == null)
            {
                return NotFound();
            }

            var especialidad = await _context.Especialidades
                .FirstOrDefaultAsync(m => m.Id == id);
            if (especialidad == null)
            {
                return NotFound();
            }

            return View(especialidad);
        }

        // POST: Especialidades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Especialidades == null)
            {
                return Problem("Entity set 'CitasMedicasContext.Especialidades'  is null.");
            }
            var especialidad = await _context.Especialidades.FindAsync(id);
            if (especialidad != null)
            {
                _context.Especialidades.Remove(especialidad);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EspecialidadExists(int id)
        {
          return (_context.Especialidades?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CitasMedicas/CitasMedicas/Views/Especialidades/Create.cshtml
@model CitasMedicas.Models.Especialidad

@{
    ViewData["Title"] = "Create";
}

<h1>Creación</h1>

<h4>Especialidad</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DescripcionEspecialidad" class="control-label"></label>
                <input asp-for="DescripcionEspecialidad" class="form-control" />
                <span asp-validation-for="DescripcionEspecialidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CitasMedicas/CitasMedicas/Views/Especialidades/Delete.cshtml
@model CitasMedicas.Models.Especialidad

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>Está seguro de borrar la Especialidad??</h3>
<div>
    <h4>Especialidad</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DescripcionEspecialidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DescripcionEspecialidad)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CitasMedicas/CitasMedicas/Views/Especialidades/Details.cshtml
@model CitasMedicas.Models.Especialidad

@{
    ViewData["Title"] = "Details";
}

<h1>Detailles</h1>

<div>
    <h4>Especialidad</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DescripcionEspecialidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DescripcionEspecialidad)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CitasMedicas/CitasMedicas/Views/Especialidades/Edit.cshtml
@model CitasMedicas.Models.Especialidad

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Especialidad</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="DescripcionEspecialidad" class="control-label"></label>
                <input asp-for="DescripcionEspecialidad" class="form-control" />
                <span asp-validation-for="DescripcionEspecialidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CitasMedicas/CitasMedicas/Views/Especialidades/Index.cshtml
@model IEnumerable<CitasMedicas.Models.Especialidad>

@{
    ViewData["Title"] = "Index";
}

<h1>ESPECIALIDAD</h1>

<p>
    <a asp-action="Create">Nueva Especialidad</a>
</p>
<table class="table" id="dataTableId">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DescripcionEspecialidad)
            </th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DescripcionEspecialidad)
            </td>
            <td>
                    <div class="actionsContainer">
                        @Html.Raw($"<a href='{Url.Action("Edit", "Especialidades", new { id = item.Id })}' class='btn btn-warning tableActionsBtn'><i class='fas fa-edit'></i></a>")
                        @Html.Raw($"<a href='{Url.Action("Details", "Especialidades", new { id = item.Id })}' class='btn btn-primary tableActionsBtn'><i class='fas fa-info-circle'></i></a>")
                        @Html.Raw($"<a href='{Url.Action("Delete", "Especialidades", new { id = item.Id })}' class='btn btn-danger tableActionsBtn'><i class='fas fa-trash'></i></a>")
                    </div>
                
            </td>
        </tr>
}
    </tbody>
</table>