CitasMedicas/CitasMedicas/Models/Medicamento.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CitasMedicas.Models
{
    public class Medicamento
    {
        [Display(Name = "Id Medicamento")]
        public int Id { get; set; }
        [Display(Name = "nombre del Medicamento")]
        public string? NombreMedicamento { get; set; }
        [Display(Name = "Fecha de Registro")]
        public DateTime FechaRegistro { get; set; }
        [Display(Name = "Stock")]
        public int StockMedicamento { get; set; }
    }
}

CitasMedicas/CitasMedicas/Controllers/MedicamentosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CitasMedicas.Data;
using CitasMedicas.Models;
using Microsoft.AspNetCore.Authorization;

namespace CitasMedicas.Controllers
{
    [Authorize]
    public class MedicamentosController : Controller
    {
        private readonly CitasMedicasContext _context;

        public MedicamentosController(CitasMedicasContext context)
        {
            _context = context;
        }

        // GET: Medicamentos
        public async Task<IActionResult> Index()
        {
            
            
            string tipoUsuario = HttpContext.Session.GetString("TipoUsuario");
            string userName = HttpContext.Session.GetString("UserName");

            ViewBag.TipoUsuario= tipoUsuario;
            ViewBag.Username = userName;

            return _context.Medicamentos != null ? 
                          View(await _context.Medicamentos.ToListAsync()) :
                          Problem("Entity set 'CitasMedicasContext.Medicamentos'  is null.");
        }

        // GET: Medicamentos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Medicamentos == null)
            {
                return NotFound();
            }

            var medicamento = await _context.Medicamentos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (medicamento == null)
            {
                return NotFound();
            }

            return View(medicamento);
        }

        // GET: Medicamentos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Medicamentos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NombreMedicamento,FechaRegistro,StockMedicamento")] Medicamento medicamento)
        {
            if (ModelState.IsValid)
            {
                _context.Add(medicamento);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(medicamento);
        }

        // GET: Medicamentos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Medicamentos == null)
            {
                return NotFound();
            }

            var medicamento = await _context.Medicamentos.FindAsync(id);
            if (medicamento == null)
            {
                return NotFound();
            }
            return View(medicamento);
        }

        // POST: Medicamentos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NombreMedicamento,FechaRegistro,StockMedicamento")] Medicamento medicamento)
        {
            if (id != medicamento.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(medicamento);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MedicamentoExists(medicamento.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(medicamento);
        }

        // GET: Medicamentos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Medicamentos == null)
            {
                return NotFound();
            }

            var medicamento = await _context.Medicamentos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (medicamento == null)
            {
                return NotFound();
            }

            return View(medicamento);
        }

        // POST: Medicamentos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Medicamentos == null)
            {
                return Problem("Entity set 'CitasMedicasContext.Medicamentos'  is null.");
            }
            var medicamento = await _context.Medicamentos.FindAsync(id);
            if (medicamento != null)
            {
                _context.Medicamentos.Remove(medicamento);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MedicamentoExists(int id)
        {
          return (_context.Medicamentos?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CitasMedicas/CitasMedicas/Views/Medicamentos/Create.cshtml
@model CitasMedicas.Models.Medicamento

@{
    ViewData["Title"] = "Create";
}

<h1>Creación</h1>

<h4>Medicamento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NombreMedicamento" class="control-label"></label>
                <input asp-for="NombreMedicamento" class="form-control" />
                <span asp-validation-for="NombreMedicamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaRegistro" class="control-label"></label>
                <input asp-for="FechaRegistro" class="form-control" />
                <span asp-validation-for="FechaRegistro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StockMedicamento" class="control-label"></label>
                <input asp-for="StockMedicamento" class="form-control" />
                <span asp-validation-for="StockMedicamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CitasMedicas/CitasMedicas/Views/Medicamentos/Delete.cshtml
@model CitasMedicas.Models.Medicamento

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>Está seguro que quiere Eliminar?</h3>
<div>
    <h4>Medicamento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreMedicamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreMedicamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaRegistro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaRegistro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StockMedicamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StockMedicamento)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CitasMedicas/CitasMedicas/Views/Medicamentos/Details.cshtml
@model CitasMedicas.Models.Medicamento

@{
    ViewData["Title"] = "Details";
}

<h1>Detailles</h1>

<div>
    <h4>Medicamento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreMedicamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreMedicamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaRegistro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaRegistro)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StockMedicamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StockMedicamento)
        </dd>
    </dl>

</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CitasMedicas/CitasMedicas/Views/Medicamentos/Edit.cshtml
@model CitasMedicas.Models.Medicamento

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Medicamento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NombreMedicamento" class="control-label"></label>
                <input asp-for="NombreMedicamento" class="form-control" />
                <span asp-validation-for="NombreMedicamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaRegistro" class="control-label"></label>
                <input asp-for="FechaRegistro" class="form-control" />
                <span asp-validation-for="FechaRegistro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StockMedicamento" class="control-label"></label>
                <input asp-for="StockMedicamento" class="form-control" />
                <span asp-validation-for="StockMedicamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CitasMedicas/CitasMedicas/Views/Medicamentos/Index.cshtml
@model IEnumerable<CitasMedicas.Models.Medicamento>

@{
    ViewData["Title"] = "Index";
}

<h1>MEDICAMENTOS</h1>

<p>
    <a asp-action="Create">Crear</a>
</p>
<table class="table" id="dataTableId">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NombreMedicamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaRegistro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StockMedicamento)
            </th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreMedicamento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaRegistro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StockMedicamento)
            </td>
            <td>
                    <div class="actionsContainer">
                        @Html.Raw($"<a href='{Url.Action("Edit", "Medicamentos", new { id = item.Id })}' class='btn btn-warning tableActionsBtn'><i class='fas fa-edit'></i></a>")
                        @Html.Raw($"<a href='{Url.Action("Details", "Medicamentos", new { id = item.Id })}' class='btn btn-primary tableActionsBtn'><i class='fas fa-info-circle'></i></a>")
                        @Html.Raw($"<a href='{Url.Action("Delete", "Medicamentos", new { id = item.Id })}' class='btn btn-danger tableActionsBtn'><i class='fas fa-trash'></i></a>")
                    </div>
                
            </td>
        </tr>
}
    </tbody>
</table>